import 'package:flutter/material.dart';
import 'dart:math';


class AquariusInfo{

  int num=0;

  List<String> _aquariusInfo=['Aquarians are intellectual, contemplative and independent. They are natural thinkers and visionaries. They spend a lot of time contemplating projects and plans. They are often interested in charity or raising money for noble causes. They are social butterflies and make friends pretty effortlessly. They can be quite stubborn. They get bored quite quickly and thus crave constant stimulation. They are hungry for knowledge and are open to exploring new concepts. They do not waver from their point of view once they find their core analysis. This brings them a sense of brilliance about life and people. It can also make an Aquarian stubborn and close-minded. They like to present themselves different from the crowd by being unique, eccentric or inventive.'];


  List<String> _aquariusLove=['The bigger planets Jupiter and Saturn will be impacting your sign and the seventh house of marriage. Jupiter will be impacting the fifth house of romance in the first half of 2022. So, this is a major year for those who seek love and romance. However, Jupiter or Saturn, are not the planets for love and romance, but they are heavy planet indicating your karma and dharma. So, the transit through the first house will force you to take major decisions regarding your relationship. Saturn is the planet for delay and obstacles, so decision making can be delayed. If your mahadasa and antra dasa are promising a marriage then, you will have some opportunities to have a new relationship or marriage. Otherwise, you will be meeting people and searching for suitable alliances. This is also a year to attend many social gatherings too, in order to find likeminded people.'];

  List<String> _aquariusAdvise=['During the first half of the year Saturn will be impacting the second house of finances, so there will be some challenges. Saturn is the planet for delays and obstacles, so saving money can be a challenge. This is a time to cut your expenses; otherwise there will be long term financial issues. You want to save, but the situations may not be that favorable. Lending and borrowing money are also seen. You must not get into any complicated business deals. It will not be wise to get into any unsolicited financial dealings. When Jupiter moves out of Aquarius, it will start impacting the eighth house of volatility. So, from the later part of 2022, you will be having some challenges again. Altogether 2022 is going to be a challenging year for finances and you have to be careful.',
  'The whole year of 2022 will be very significant for your health. During the first half of the year Saturn will be moving through Capricorn and that will be impacting the health and happiness. You will have complex dreams and they will give you some signals. There are some burdens which are making your slightly discouraged. This situation will change in the second half when Saturn will move into your sign. From then onwards, you will be looking for a support as Saturn will make you feel very responsible. If you are too burdened, then you should take the support of your well wishers.The lower abdominal area will be very much triggered and you will have to be careful with your diet. If you are already suffering from any health related concern, then the first half will be a little challenging for you. So, you have to be very careful.',
  'Career related matters will be active throughout the year as Saturn will be impacting the sixth house of work in the first half and the tenth house of career in the second half. During the first half when Saturn stays in Capricorn, it will aspect the sixth house of work and colleagues. This is a very big time for those who work in creative industry as Jupiter will be impacting the fifth house. Politicians, teachers, businessman and mentors also will find this as a very important time. Projects from technical and financial domains are also seen during this year. This is the time to work in competitive projects as well. You will be looking for new opportunities at work. Please be careful with your interaction with your colleagues, otherwise there will be challenges. Please make sure, you are staying away from all gossips. This is a time to work in extra projects, mostly from the creative domain.',
  'Your investigative and inventive mind will lead you to discover something new. Your creative discovery will also bring you lot of appreciation and recognition.Implementing any new innovation may cost you dearly. Keep aside a part of your budget to incur such costs. Avoid spending on impulse and taking any gambles.You will prefer working on your own as you detest authority. You dont like people telling you what to do and how to do it.Your philosophical thoughts would act as a guide today. Rely on it completely as it will never go wrong. Also, today it will only bring you good.',
  'You will find it very difficult today to be kind to or forgive someone who has done you any harm. It requires a higher consciousness to be able to do so. But your ability to be empathetic towards everyone helps you forgive such a person.Showing tenderness and affection does not make you into a weakling. Even men are now exploring their softer, sensitive side. Be gentle and kind to yourself and others.You will meet a qualified doctor or someone equally knowledgeable who will help you out of your illusory world. It has been taking you away from the real world.Today an important issue might be brought up by your beloved. Give all your attention and priority to what seems to be the concern.Today you can expect something that refreshed and rejuvenates you. It might be a good news, or someone who makes you happy. Keep up the high spirits.',
  'Something is bothering you and you need an explanation or reason for it. Your worries can be explained away. Just act according to what you think is right.Family members, especially children will turn to you for affection and care. Women will feel very exhausted by the demands on their time.You have been haunted by illusions and nightmares for some time now. Only your own willpower will help you rid of these negative thoughts that ruin your life. Do not give in to your nightmares.Your friends and family members will help you today in your endeavor to improve your standard of life. They will guide you as you go about building a more secure life for yourself.Now is the favorable time to take new steps to make changes to your life. But this might also mean that you need to stay away from your current place.'
  ];

  String getAquariusInfo()=>_aquariusInfo[0].toString();
     

  String getAquariusLove()=>_aquariusLove[0].toString();
     

  String getAquariusAdvise(){
    num=Random().nextInt(6);
    return _aquariusAdvise[num].toString();
  }
}