import 'package:flutter/material.dart';
import 'dart:math';

class CancerInfo{

  int num=0;

  List<String> _cancerInfo=['Cancers put their wholehearted efforts into anything that they believe in. They are sensitive, receptive and emotional. They cover their soft, vulnerable side with rock-solid armour, and it is quite an effort to get through their tough exterior. They tend to be nurturing, value domesticity and family to a great deal. They believe in building a stable and safe home, as they need a reasonable amount of time to unwind and recharge. However, they can be moody and temperamental. They can be heavily influenced by the people, energy, and situations surrounding them. Slow, steady and consistent pacing is essential for Geminis as they require trusting others before letting their guards down. This can be a daunting process, and any slight mishap can put a Cancer on defence. These highly intuitive, nurturing and generous individuals love cohabiting, creating and dreaming. '];

  List<String> _cancerLove=['In 2021, you were busy dealing with your personal life and relationships. You will be able to manage your life as well as your romantic relationships better in 2022. It is a particular year for Cancerians as Saturn will be leaving your seventh house of marriage. It was burdening you by making you very stubborn, cold and impatient. By April, you will be having a different perspective about your relationships, and there will be some changes in the existing relationships. In January, Venus, the planet for love and romance, will slow down. So the initial days of 2022 might not show an easy time. Still, 2022 will make you more realistic about your relationships. This is a good year for married couples and lovers who want to strengthen their relationship. Cancerians will meet many opportunities to meet like-minded people as well.'];

  List<String> _cancerAdvise=['It is a crucial year for your career as Rahu will be coming into the sign of Aries from the mid of 2022, which will make you vigorous at work. You will get many opportunities to work with new teams. It is also a good year for foreign collaborations, and you should act with wisdom. Until Saturn moves into Aquarius, you will be trying to strengthen your career. Saturn is in a good place, but Capricorn is in its own sign, which makes you very stubborn. Being flexible will help you reap gains. There will be many opportunities for media personnel, medicos, financial analysts, and those who work in the IT sector.',
  '2022 will bring your health into focus thanks to the impact of Saturn and Jupiter on the sixth house of health and wellness. As there will be a lot of projects on hand, you will be physically tired. The neck and shoulder will be sensitive areas this year. If you experience discomfort or pain in these parts, you should take care. Your lower abdomen area will be in focus in 2022; make sure to take care of it. The lower intestine, liver and entire digestive system will need more attention. It is best to consume an organic diet as well. It will be good to avoid spicy food and foods that are too cold throughout the year. As the sixth house, related to digestion, is active, it may bring on digestive issues. You will have to spend some time strengthening your spirit. The best solution is to follow a regimen where you keep some time off for prayer and meditation.',
  'Lets be practical in 2022 as there will be finance-related issues. Being a Cancerian, you are an emotional person, and certain decisions are taken based on emotions. It is best not to do that; otherwise, you will be taking the wrong decisions regarding finances. Rahu will be forcing you to spend more money unnecessarily. This will become evident from April onwards. If you dont resist these feelings, you may end up borrowing. This can land you in unnecessary debts. There will be some financial settlements but beware of fraudulent investment plans. Business people should not be in a hurry to start partnership projects. You may receive requests for financial help, and you should deal with them appropriately.',
  'You have the ability to understand others feelings and emotions. It makes you empathize with them and their situations. But today, its best that you explain your views and opinions clearly so that you are not misunderstood.Women who dedicate their days taking care of their families need to take care of themselves as well. They shouldnt neglect their own well being.You have been suffering from hallucinations and nightmares. Today you might receive proper guidance from a qualified person who will help you rid of these.Today you will make considerable progress in your financial as well as career status. A promotion or a better paying job might be in the offing.You will soon find yourself in a new surrounding. It might be a transfer or a shift to a new place. But this move will definitely bring about a positive change in your nature.',
  'You will find it very difficult today to be kind to or forgive someone who has done you any harm. It requires a higher consciousness to be able to do so. But your ability to be empathetic towards everyone helps you forgive such a person.Working women may have to deal with problems both at home and work. It would be a difficult day for them.You will meet a qualified doctor or someone equally knowledgeable who will help you out of your illusory world. It has been taking you away from the real world.You will finally get some time today to think of yourself and your family. Youve been putting it on the backburner for some time now. You will see the benefits of doing and thinking something for the family very soon.Today you can expect something that refreshed and rejuvenates you. It might be a good news, or someone who makes you happy. Keep up the high spirits.',
  'Some of your eccentricities, which make you difficult to adjust in the public, will get ceased through your hard work and meditation. Now you will be able to deal with people more confidently.Be gentle with yourself and with your loved ones this week. Since you are under significant pressure right now, it is difficult to manage relationships. They must be going through a storm that causes them to feel defensive and fearful.Your supersensitive feelings hamper your personal progress. You need to loosen up, taking things a little less seriously rather than reacting to it.More and more ideas with novelty will come to your mind. What you need now is the support of your co-workers and the confidence to implement it successfully.Dealing with some troublesome issues will grab the time and energy of women especially those struggling between their home and career.Time is congenial to you to choose a career or commence a new venture. Forming a new base now will act beneficial for your whole future.An act of virtue, forgiving a person for his mistake that hurt you a lot, from your part will make you more respectable among people you love.As a mother, while dealing with your children, you act more like an old-fashioned person who believes more on moral principles. This will only help to get you detached from your children.Support from your relatives and friends will shower as bliss for you to lay a strong base for your future.A mood of enjoyment and refreshing will prompt you to take holiday for some days. You will feel more revitalised and energetic after this.'
  ];


  String getCancerInfo()=> _cancerInfo[0].toString();

  String getCancerLove()=> _cancerLove[0].toString();

  String getCancerAdvise(){
    num=Random().nextInt(6);
    return _cancerAdvise[num].toString();
  }
}