import 'dart:math';
import 'package:flutter/material.dart';


class CapricornInfo{

  int num=0;

  List<String> _capricornInfo=['Capricorns are patient, ambitious and reserved individuals. They desire a life that is based on a solid foundation. They are hardworking and focused on achieving career and financial success. They value long-term stable relationships. They are disciplined and determined, but sometimes to the point of austerity. Their sense of practicality makes them less emotional and is unwilling to be distracted by feelings; instead, they think it is easier to face facts. They have a great sense of humour which helps them connect better with others.'];

  List<String> _capricornLove=['This is an average year for love and romance as you will be focusing more on your personal life. This is a year for growth and taking more responsibilities than spending in love and romance. You will have to take care of your existing relationship. Saturn is the planet for delays and obstacles that will be impacting the seventh house of relationships. You need to give some space to your significant others too. They also will need some care as they are also moving through a sensitive phase. In 2022, the problematic relationships will move forwards, and you will make major decisions regarding your relationship. There is nothing wrong with being flexible and sacrificial in relationships. New people may come into your life. Social gatherings will keep you busier, and you will be looking for new opportunities, which will help you grow.The yearly horoscope 2022 will be an average year for married couples, too, as they have multiple things to take care of. However, there will be some lighthearted moments also going to come up. Please try to understand the needs of your spouse.Generally, your spouse can be very emotional by nature and they will be somewhat demanding during 2022. This is also a year for couples who are in long-distance relationships. They will get many opportunities to meet more often than ever. That will surely bring you both closer to each other. There will be a lot of events at home, and both of you have to focus on that.'];

  List<String> _capricornAdvise=['This year is crucial for Capricorn as your lord Saturn will be impacting your personal life and finances. Jupiter, Rahu, and Ketu will also hold significant roles in your life. In 2022, the first portion of your horoscope will be active, and you will be focusing on your personal growth and family, your career, and your money. When Saturn moves to the water sign of Pisces, you will have plans for real estate deals. This is a time to meet your relatives, and they may share their concerns with you. Saturn is the planet for land-related contracts, and you will deal with such activities. There will be a lot of team ventures, and you expect occasional financial gains as well. You will be getting new long term projects, too. This is also a year to interact with large groups, and you will be busy with team discussions.Projects from foreign lands also will be a part of 2022. You need to drink more water and have organic meals. This is also the time to take up a new health care regime. Through the eleventh house of long-term relations, the transit of Ketu can make you dominate your team settings and create unhappy confrontations. Your teammates will undoubtedly have different views, and you need to accept them. This is a year to network and thus meet people from other places. You will have to be careful with your travel plans as there are chances for obstacles. You will be interested in knowing more about spirituality and theology. Please dont take solo decisions regarding your ventures. If you are a share broker, please take fewer risks. Please be careful with children and youngsters around you. However, sudden expenses are also expected. You will get many opportunities to have a good relationship with your partners. Please try to avoid complex financial deals as they can confuse you. New business contracts and deals can also come up. Long trips and job opportunities will also be a part of this year, making you feel optimistic. Those who work in media and communication will have to be very careful with their projects. Otherwise, you may end up reworking the entire job. Part-time projects can also come up. You will have to deal with the issues in tax, insurance, and PF issues. There will be lending and borrowing, be cautious.',
  'In 2022, you will be very much focused on your career and your business. Throughout this transit, you will be curious about your social image and professional responsibilities. Throughout 2022, Saturn will be impacting your personal life, official relationships and career. Please be careful; otherwise, there will be challenges and delays in the projects. They can come as rework and sudden changes in the existing project. In 2022, Capricorns can get new job offers, but please dont hurry to accept them. Managers can be very accountable, so you should focus on the quality of your work. You will have to argue with your colleagues at work, so you have to keep a healthy distance from your colleagues. Business owners will find this an important year, especially when Jupiter moves into Aquarius. Then onwards, there will be blocks in own ventures. If you are looking for a transfer, this is the right time to get that.During the second portion of the year 2022, Jupiter will be moving into the sign of Pisces, which will help you improve the business venture. You may have to restart everything and take up new plans for your business. Still, it would help if you remembered that Jupiter is not the planet for business, and it is the planet for consulting and advising. So, you need to consult an expert before you start a new venture or adopt a new plan. Please dont expect all the plans to be a success. Be practical and logical, and that can avoid risks.',
  'The year 2022 will be an average year for your health, but you can expect minor issues. If you are already suffering from any health issues, you have to be careful. In 2022, all the houses will be active, and the health-related challenges also will be activated. The temporary challenges should not be ignored. The planet for longevity, Saturn, will be in your first house of health, so you may feel a little more burdened and aged. However, that is not a matter to get worried about. The woman has to be very careful with the health of the reproductive organs. Those already on the medication for uterus related issues have to be very careful. Like every year, you will have to focus on a good diet. Kindly avoid taking these items, which can trigger acidity and breathing issues. Prayer and meditation also will be very important during this year. The yearly horoscope 2022 shows a lot of focus on the neck to the shoulder area. You will have a lot of work, which will be very complex. If you are already struggling with ENT issues, you have to take care of that and please dont delay your meeting with the ENT specialist. Capricorn natives will have to take care of their emotional health more than health issues. When Jupiter moves into Pisces, you will have some concerns regarding finances and home. On a positive note, Saturn is the planet for longevity, and when it moves into Aquarius, you will see improvement. However, you should not stop working out and dont ignore the symptoms. Please take regular checkups too, so that you can be fit and strong throughout the year.',
  'Financial matters will be the highlight of 2022 as Saturn and Jupiter will be impacting the second house of finances. You will be highly tempted to spend more on luxury items, a big problem. Please try to control your expenses; otherwise, there will be long term financial issues. You are very intelligent in investing, but you can be overconfident when Jupiter is in the second house. Please try to invest after getting the right advice. Kindly avoid fancy financial deals. Your ruler Saturn is the planet for Karma, and that will block you if you are making money through unsolicited deals. Ketu will be impacting the finances and gains during the first half of the year. That time, you should not take any risk by taking up huge investments. This is not the year to invest wherever you want. However, you will have enough money for your needs.The yearly horoscope 2022 shows that April will be of a huge planetary influence. During April, Jupiter, Saturn, and Rahu will be changing the signs. So, this is not a time to take risks with your finances, too, around the time of April. Kindly avoid huge risk from the mid-portion of 2022 as Saturn will be in the sign of Aquarius for the long term. You may have to make new financial plans to strengthen your finances. The focus should be on savings that expense, and you need to apply this strategy for the next two and a half years.',
  'You will find it very difficult today to be kind to or forgive someone who has done you any harm. It requires a higher consciousness to be able to do so. But your ability to be empathetic towards everyone helps you forgive such a person.Showing tenderness and affection does not make you into a weakling. Even men are now exploring their softer, sensitive side. Be gentle and kind to yourself and others.You will meet a qualified doctor or someone equally knowledgeable who will help you out of your illusory world. It has been taking you away from the real world.Today an important issue might be brought up by your beloved. Give all your attention and priority to what seems to be the concern.Today you can expect something that refreshed and rejuvenates you. It might be a good news, or someone who makes you happy. Keep up the high spirits.',
  'Some of your eccentricities, which make you difficult to adjust in the public, will get ceased through your hard work and meditation. Now you will be able to deal with people more confidently.Be gentle with yourself and with your loved ones this week. Since you are under significant pressure right now, it is difficult to manage relationships. They must be going through a storm that causes them to feel defensive and fearful.Your supersensitive feelings hamper your personal progress. You need to loosen up, taking things a little less seriously rather than reacting to it.More and more ideas with novelty will come to your mind. What you need now is the support of your co-workers and the confidence to implement it successfully.Women may not enjoy their day at work. Something relating to your finance may cause worry. But you will not fail to put in as much of effort as you generally do. You must maintain a cautious behaviour at your place of work.You have the ability this week to turn that which appeared negative or wasted, into a new form with good potential for improvement. Communications with partners, clientele and significant others will be productive at this time. Future looks good indeedAn act of virtue, forgiving a person for his mistake that hurt you a lot, from your part will make you more respectable among people you love.In your search for professional glory, you may miss out on the finer and more important aspects of your life, your children! Keep the mother in you alive and life should turn out to be one happy-go-lucky ride!Support from your relatives and friends will shower as bliss for you to lay a strong base for your future.A mood of enjoyment and refreshing will prompt you to take holiday for some days. You will feel more revitalised and energetic after this.'
  ];

  String getCapricornInfo()=> _capricornInfo[0].toString();

  String getCapricornLove()=> _capricornLove[0].toString();

  String getCapricornAdvise(){
    num=Random().nextInt(6);
    return _capricornAdvise[num].toString();
  }
}