import 'dart:math';
import 'package:flutter/material.dart';


class GeminiInfo{
  int num=0;

  List<String> _geminiInfo=['Geminis are curious about everything. They are quick-witted and have a philosophical view of the world. They are excitable and ready to learn about everything. They are flexible and versatile and are masters of communication adept at connecting with others. They have a double-sided personality, which is shown to the world while the other is kept hidden from others. They are highly adaptable and can process things through their minds rather than just their emotions. Geminis are best known for their talkative, spontaneous, and upbeat dispositions. However, they can be too fickle and gossipy, leading to many assumptions. '];

  List<String> _geminiLove=['2022 is not a good year for love or marriage, but that doesnt mean 2022 will be a bad year either. You will have many opportunities to improve your life. Jupiters aspect on the seventh house of marriage will bring some relationships. However, Jupiter is not an ideal planet to be in the house of marriage, as it is not the planet for romance. It is the planet for spirituality, so there are chances for misunderstandings as well. Singles will get opportunities to meet like-minded people and thus start a new relationship in 2022. However, it would help if you were careful with whomever you meet. Venus will be slowing down in January, so the first months of the year may not be great for such relationships. However, married couples will be able to improve their ties during this year. Geminis will be very serious this year, which is good, in some ways, for their personal life. Usually, Geminis are social butterflies, and they have less control over their communication. This year, Mercury will also be in a slow down mode during every quarter, posing another challenge. So during these times, you should stay away from taking on commitments. Instead, Geminis should give more priority to their personal life and growth.'];

  List<String> _geminiAdvise=['In 2022, Geminis will feel the burden of responsibility because Saturn will be aspecting your sign. It will make you reliable, but you might be overburdened. The planet will impact the seventh house of career, and you might get a significant role, so there will be some important projects. In 2022, you will be looking for new opportunities, and you will be getting them. It is a significant year for job seekers too. Long trips and career-related training will be important themes during this year. Those who work in media, sales, and marketing will be getting new opportunities. A busy year is foreseen as new team opportunities, and long term projects will be coming up during this year. Business owners also will be very busy. They will have to be careful with their partners. Especially until Saturn moves to Aquarius, there will be challenges from the business. Please be cautious if you are a person who rolls money for business purposes. The entire world is going through Covid related challenges, and it is not going to end soon.',
  'It is a complex year for your emotional needs, so you have to be careful. Saturn and Jupiter will be impacting the struggles, and you have to, first of all, take care of your health. It is not the time to go for financial plans that may not suit you. It will be a challenge, and it will likely cause you stress. In 2022, you will have to be very careful with your food habits as well. If you already have a health issue, then you need to take precautions. It will be good to start a workout regimen and meet a dietitian who can help you plan your meals according to your bodys needs. The lower portion of the body will be highlighted, so you have to focus on that area.',
  'The highlight of 2022 will be your money matters as multiple planets will be activating the finances. There are chances for lending and borrowing but dont overdo it. Otherwise, there will be long term hassles and financial issues. This year is not so great for new partnerships based on the finances. You will be focusing on PF, insurance and taxes. However, as you advance through 2022, you will get clear ideas about managing the finances. You will be getting multiple opportunities for setting long term projects. You will have a particular focus on your finances as well. However, you will have unexpected expenses throughout the year, and you have to be prepared for that.',
  'Start referring to books related to what you intend to do. Such books will guide you in making successful plans.Today you may feel exhausted of the demands made on you at home as well as at work. You need to take some time out and think and plan your work. For all you know, you might be doing something the hard way.It would be good if you do not take any risks in business or industrial matters. Such a risk might jeopardize you and your position.Try and analyze the reasons or basis for the interest you have developed in a new acquaintance. Do not place your trust on anyone before you know them well.Your habit of thinking beyond the good and the bad and of finding something wonderful about others will gain you loyalties of those around you. They will be loving and true to you.',
  'You may feel drained of all your energy as you it gets wasted on an unsuccessful project youve taken up. Stop wasting your time and energy and take up something that would refresh you.Your emotional vulnerability and lack of physical energy will make you very cautious in all your interactions today.Today you will finally meet someone who is interested in your talents and tastes. You have not been devoting enough time on them to cope with the pressures of your busy schedule. This will bring an outlet for all that stress.',
  'More and more project ideas will come to you. Your ability to experiment will help you choose the best out of it.The efforts you put into your ventures till now, will start attaining benefits. For the time being, you can just sit down and relax. Then you can start plucking the ripe fruits of your hard labour.You are pressed to retrace back in the workplace or with your partner. A critical situation is developing around you and though it gets on your nerves, you may be the only one who can appear to remain calm and unbiased.Being feeling insecure, you really need the help of someone to boost your energy and enthusiasm.Your romantic reverie is far more a journey into fantasy-land than an earthbound evening of parties and dances.You are a person who is attracted towards novelties. This will bring you attached to some new projects which are sure to gain you profit without much delay.Your ego and pride can become shackles that hamper your progress in life. It will only be wise to mingle more with those you deal with and accept their advice to reach your motive.As a born leader, you are a pioneer with a purpose. You tend to reach your goals in straightforward ways and without hurting anyone.Your ability to remain silent, humble and flexible when it is not necessary to air your views will bring more recognition for you among others. You can very well present your philosophical insights when it is in need.The main menace to your physical situation will be your emotions, which in the form of repressed anger and grudges can even lead to a mental syndrome.'
  ];
  
  String getGeminiInfo()=> _geminiInfo[0].toString();

  String getGeminiLove()=> _geminiLove[0].toString();

  String getGeminiAdvise(){
    num=Random().nextInt(6);
    return _geminiAdvise[num].toString();
  }

}