import 'dart:math';
import 'package:flutter/material.dart';


class LibraInfo{

  int num=0;

  List<String> _libraInfo=['Libras value peace and balance in life. They are charming, social and diplomatic individuals who make every effort to be fair in life and their relationships. They possess a natural tendency to surround themselves with beauty and luxury. They are considered eternal romantics as they desire relationships and are ready to take the plunge headfirst when they find someone they admire deeply; however, this could lead them to co-dependency. They are excellent negotiators having gifted in communication. They process their feelings intellectually; needless to say, they are also deeply sensitive individuals. They can be indecisive and can do everything possible to avoid conflicts. They are flirty by nature. Their intelligence charms others and makes them good company to others. They are perfectionists who flourish with order and balance. Libras are socially curious and are interested in human interactions and thoughts. They keep an eye on what is fair and strive to be impartial while hearing both sides of the argument and not jumping to conclusions or reacting out of anger.'];

  List<String> _libraLove=['The year 2022 will be very important in love and romance. The beginning of the year will be not very good for all the signs as Venus; your ruler will slow down the planet for love and romance. This slowdown will impact everyones love life in a complex mode.The situation will slowly change, but it will not be smooth as Jupiter moves into the sign of Pisces.When Jupiter is in the sign of Aquarius, single Libra natives will think about getting married. If the maha Dasha and Antar dasa is supporting a marriage, then Libra natives will get married. Otherwise, they will find someone whom they like, and some people may postpone the decision for matrimony. However, 2022 will be a big year for married couples as well.'];

  List<String> _libraAdvise=['Throughout the year, multiple planets will impact your career and business. This is a challenging phase for business owners, and they have to stay away from anything risky. Saturn will be in the sign of Capricorn until the mid-portion of the year, and in April 2022, it will move into the sign of Aquarius. When it is Capricorn, Saturn will be blocking the progress in the business, and that doesnt mean there will not be any progress. The challenges will be evident when Saturn is about to leave for Aquarius. During its plight through Aquarius, those in business will have a lot of work. This is also a year for those who look for a job change or a new job. During the second half of the year, there will be a lot of opportunities to improve your business ventures. Still, it would be best if you were very careful with the terms and conditions of the business agreements.',
  'This is a very important year for mothers to be and couples who want a child. Until April 2022, Jupiter will be in the sign of Aquarius, and this is a good time to get conceived, so the pregnant woman has to take care of their health and medication. The transit of Saturn through the sign of Aquarius will bring health-related concerns. The lower abdomen area will be very much active during this year. If you are taking the wrong diet, it will trigger lifestyle diseases, so you have to take care of the diet. Throughout the year 2022, you may feel a little down about health, but from April 2022 onwards, you will be able to handle your health-related concerns. During March, June and October, your ruler Mercury will be moving in a slow down mode, and this time can bring some stress, so you have to be careful.',
  'This is a progressive year for finances, but the beginning of 2022 will be challenging as the ruler of your finances, Venus, will be in a slow down mode during the first month. So, the first month of the year 2022 will be of challenges, but you should not get discouraged. This year will you will be able to have stability in your income. The more giant planets, Saturn will be aspecting the second house of savings and wealth. There you will get enough opportunities to make better plans for your finances. You can also expect some financial adjustments. You will be able to settle or restructure your debts in 2022. You will be very cautious about your wealth, and please try to make better plans with the help of financial experts. You will indeed have some profits from your ventures.',
  'Today you may feel exhausted of the demands made on you at home as well as at work. You need to take some time out and think and plan your work. For all you know, you might be doing something the hard way.Lack of physical stamina will lead you to procrastinate. You wont be up to implementing your ideas instead you would spend your time thinking and analyzing.You will find time today to pursue your favorite hobbies and interests. This will refresh and invigorate you. And also create a mental balance as all work and no play makes you a dull person.',
  'Being feeling insecure, you really need the help of someone to boost your energy and enthusiasm.More and more ideas with novelty will come to your mind. What you need now is the support of your co-workers and the confidence to implement it successfully.You will meet some respectable people who will help you find a way out of your delusions. This will also boost up your creative talents.Your ego and pride can become shackles that hamper your progress in life. It will only be wise to mingle more with those you deal with and accept their advice to reach your motive.Support from your relatives and friends will shower as bliss for you to lay a strong base for your future.Compulsive eating and escape motivated drinking can ruin your health. Meditation and self-control will help you to get rid of this situation.You have been kept tacit for some time about your wishes like wandering around or hitchhiking, mainly because of money and time. Now everything will come in favour of you for doing something which makes you pleasant.The less time you spend thinking about yourself by mingling with more and more people will present you with some romantic moments.Separation from your family will be a new experience for you. But these changes will make you more independent and confident to face any hazards in the life.A thorough analysing of the situation will only shower on you the best, whether it is for beginning a new venture or choosing a life partner.',
  'As a Libra guy in the first month of 2022, you may feel a little obsessed with your love life. The feeling that something is wrong or may go wrong will drive you to the edge of sanity. You will start taking note of everything that occurs, from fabulous dinners to every casual word spoken. You will analyze every body movement of your lover and check for hidden messages. If you fail to keep up a good sense of humour and not be open and accommodating, an implosion is likely. However, things will be different if you are single. If you have a crush on someone, it is best to reveal it during the initial period of the month. If you are looking to hook up with someone, you may go ahead and utilize all your options online and meet in person. However, do not play with your or the other persons emotions or else the experience will end badly for you. Take care not to mistake freedom as an excuse to be irresponsible. Also, do not do anything reckless that may come back to haunt you later in life. Misunderstandings will be a part of life. You will not get your idea across to your friends and colleagues. It will also cause problems in your love and family relations. It is better to not talk too much or take the initiative during January. Still, you need to chase your goals to the fullest regarding work-life. You will be seeking solace from problems in relationships in your work. Make sure you appear well-dressed and neatly trimmed during meetings. Some good news may arrive at this time. It may be a promotion, or it may be a better job offer from another company. Be alert always, as an opportunity may arise anytime from anywhere. While it is not advised to take the initiative, you are more than welcome to participate in group activities. Being part of charity works and social groups will do good for your mind and is also a good way to meet new people. This will keep away problems you may experience on the relationships front. On the whole, while January will bring its share of problems and miseries, you will also receive the knowledge and wisdom to overcome it as a Libra guy.'
  ];

  String getLibraInfo()=> _libraInfo[0].toString();

  String getLibraLove()=> _libraLove[0].toString();

  String getLibraAdvise(){
    num=Random().nextInt(6);
    return _libraAdvise[num].toString();
  }
}