import 'dart:math';
import 'package:flutter/material.dart';


class PiscesInfo{

  int num=0;

  List<String> _piscesInfo=['Pisces are incredibly emotional and can typically engage themselves into a group very quickly. They have a healing quality that helps others which can sometimes be too overwhelming. They are imaginative and intuitive and often old souls. They have an innate connection with the spiritual and mystical world. They are often attracted to deeply romantic, creative or transformative experiences. They are compassionate. They enjoy a vivid social life with exceptional people and make excellent friends. They are greatly empathic and can tune into the energy that most people ignore. Unfortunately, they tend to become overwhelmed or impressionable to others depending on the amount of information they receive, making them break free and move on to a new journey, unafraid to recreate themselves.'];

  List<String> _piscesLove=['The first half of the year may not be great for love life as any of the giant planets impact love-related matters. However, the minor planets will be moving through the fifth and seventh houses, giving many opportunities for meeting some people, but that may not end in an affair or marriage. For marriage, the mahadasa and the antardasa will have to operate. If you are of marriageable age and your dasa also favours a marriage, you can have a marriage. However, Jupiter or Saturn is not the planets for love and marriage. So, this is a year to focus on your existing relationships and improve them. You will have to be very careful with the current relationship, especially when Jupiter moves into your sign in April. That will be bringing more karmic baggage into your relationship.'];

  List<String> _piscesAdvise=['This is a very challenging time for your career as Saturn will be in the eleventh house of team settings and will move into Aquarius by April. When it is Aquarius, it will bring more focus at work. Before then, when Saturn is in Capricorn, you will try to make new long-term goals. During this time, you may go through foreign collaborations. This is an excellent time to join a new organization or team.So, job seekers will have to be very careful with this opportunity. When Saturn Move into Aquarius, Saturn has some challenges arising from the workplace. There are chances for arguments with your colleagues, so please avoid all disputes. During this year, there are chances for foreign travels and long trips. These trips can be for career-related studies as well. You will be learning new skills during this year.',
  'Throughout 2022, your health will be significant as Saturn and Jupiter will aspect the sixth house of health and wellness. The emotional needs will also be impacted, which will be another challenge. Please be careful with your food and diet, because that will decide health improvement. You must be careful with your lower abdomen area as the sixth house indicates that area. Being a Pisces, you are an imaginative person, so there will be some issues regarding your emotional health. It will be good if you take the help of a spiritualist to deal with your problems. You may even join a gym or a health care program. Jupiter will move into the sign of Pisces; it will help you to be a spiritual person. There will be a lot of happiness in the second half of 2022.',
  'The first half of the year will be significant for your gains. You will get money as you will be focused on your long term gains, which will give you profits, but steadily. There will not be sudden or unexpected gains. You will be working hard, which will provide you with gains and be happy. During the second half of 2022, Jupiter will be bringing new business opportunities, which will be an excellent opportunity to gain further. Please be careful with the business ventures and not hurry. Saturns aspect on the second house will make you very practical about money. This aspect will help you to save more than you expected. You will grow systematically in finances, and you will start a new savings plan as well. Please spend less so that you can feel safe.',
  'The year 2022 will be a great year to grow and learn for those falling under the zodiac sign of Pisces. The planets Jupiter and Saturn will be making you more mature and practical. This is an excellent time to join a new organisation or team. New friends can also come up. Meeting new people and gaining further information will be part of this year. Please try to explain everything with clarity, especially at your work. You may have to do some rework. Those projects can be mainly from technical communication-related sectors. Try to work on projects that have been around for some time to bring more perfection; avoid new works. Charitable activities are also a good option this year as they bring you peace of mind and happiness. Those who run their ventures will try to expand them. Those working with share broking and other speculative ventures should be careful as this year can be volatile. You may feel that everything can be taken lightly during this phase. But it would help if you avoided the tendency to be so. During this year you will feel very relaxed, and you would like to participate in social gatherings. You will be working for the nourishment of children and young age groups. You may have some concerns regarding your health. It is a time to revive your health and beauty. Renovation and construction at home also will be part of 2022. It is a great year to meet with your family members and friends. It is a perfect opportunity for communication-based jobs. You may get the chance to work in media as well.There may be more than regular interaction with your siblings or people like your siblings. This is also a year to enjoy with your children and friends. The mahadasa and antardasa are very important, and you should cross-check with the strength of the dasa. It will be best to refrain from unwanted activities as there might be long term challenges. New projects can come up, so this is an excellent opportunity for job seekers. You may take up new healthcare programs as well. It would help if you focused on savings as there are challenges regarding finances. This year will bring some money from your hobbies as well. You may have to solve some issues at home. Altogether, this is a hectic year for you, but there are travel plans, too.',
  'Your peculiarities, which were a source for others to make fun of you, will bring some advantages for you this week. You will find yourself a central figure in some parties or public gatherings.Be gentle with yourself and with your loved ones this week. Since you are under significant pressure right now, it is difficult to manage relationships. They must be going through a storm that causes them to feel defensive and fearful.Dear and near ones will act in such a way that you will find yourself facing a mental trauma. Better stay calm, as you are the one who is expected for the time being to react normally.Backing from your friends and those assisting you will help you. this week, to make a dream come true. Patience from your side to accept the advice of others is also needed.Dealing with some troublesome issues will grab the time and energy of women especially those struggling between their home and career.Time is congenial to you to choose a career or commence a new venture. Forming a new base now will act beneficial for your whole future.To err is human and to forgive is divine. You will feel much relieved by getting pardoned from your dear one for your mistake you go through accidentally.As a mother, while dealing with your children, you act more like an old-fashioned person who believes more on moral principles. This will only help to get you detached from your children.Whatever be your specific career choice, the combinations of your tenacity and sheer endurance will prove to be a winning one. Personally, this week will prove to be a stepping stone to your augmentation either financially or career wise.You wield a lot of power and love new projects, people and interests. The optimistic nature will help you feel rejuvenated.',
  'Something is bothering you and you need an explanation or reason for it. Your worries can be explained away. Just act according to what you think is right.Family members, especially children will turn to you for affection and care. Women will feel very exhausted by the demands on their time.You have been haunted by illusions and nightmares for some time now. Only your own willpower will help you rid of these negative thoughts that ruin your life. Do not give in to your nightmares.Your friends and family members will help you today in your endeavor to improve your standard of life. They will guide you as you go about building a more secure life for yourself.Now is the favorable time to take new steps to make changes to your life. But this might also mean that you need to stay away from your current place.'
  ];

  String getPiscesInfo()=> _piscesInfo[0].toString();

  String getPiscesLove()=> _piscesLove[0].toString();

  String getPiscesAdvise(){
    num=Random().nextInt(6);
    return _piscesAdvise[num].toString();
  }
}