import 'dart:math';
import 'package:flutter/material.dart';


class SagittariusInfo{

  int num=0;

  List<String> _sagittariusInfo=['Sagittarians are adventurous, optimistic and spontaneous. They refuse to be confined and crave everything that life has to offer. They are curious, energetic and philosophical. They love to travel and have a great sense of humour. They love the outdoors and prosper in new opportunities. They are sojourners. They are impulsive and restless and may find it hard to focus on one thing at a time. They fear commitment and responsibility. However, Sagittarians are born to be free, and this sunny energy often brings them a natural form of luck.'];

  List<String> _sagittariusLove=['Your love life will be very eventful as Rahu and Ketu will be on the axis of Aries and Libra, and for you, these signs rule the romance and team settings. However, at the beginning of 2022, there would not be any substantial planetary influence on these houses. So, you will find changes after when Rahu Ketu change the signs. You will have to focus on your financial matters and own ventures until then. During the second part of 2022, you will be getting many opportunities to meet like-minded people, and they will come to you as well. There will be group meetings and social gatherings during this time. Being a Sagittarius and being naturally optimistic may make you jump into relationships. Such moves can put you into trouble. So, you will have to be careful with whom you meet and share your feelings with. This is a very significant year for all, but those who are in a long-distance relationship will find more intensity. It is very important to meet frequently during 2022. Otherwise, some misunderstandings will creep up, which can harm the relationship. It would help if you found more time with your lover in an offline mode. That will help you understand the issues with each other and solve them. Solving problems will be a little challenging, but if you are spending enough time, you will be able to solve the issues. However, you will be thinking more about love during this transit.'];

  List<String> _sagittariusAdvise=['The first half of 2022 will be very important for your finance and career. Saturn will be in the second house-elf career, and there will be some challenges at work. That will bring you complex projects, and that will make you impatient. However, these projects will help boost your image in the workplace. There will be some new job opportunities as well. Part-time projects can also come up during this phase. From April onwards, there will be some changes in the workplace. Those looking for a transfer or career-related travelling will also get such opportunities. This is a very important time for those who work in media and mass communication. However, there will be multitasking, and you have to be physically prepared for that. Business owners will be hardworking during 2022, and this year can be a productive year for them. However, please avoid risky ventures.There will be many long-term projects with minute details, and you have to spend a long time on that. These projects will be very time consuming, so you may at times feel tired. Please be polite when you deal with your colleagues, clients and employers. At times, you may lack patience, and that can be challenging.During every Mercury retrogression, the chances for delay will be coming up. During March, June and October, Mercury will turn retrograde, so you will have to take care of your projects more during that time.Please think twice before you sign any documents, especially during the Mercury retrogression phase.',
  'Your physical health will be very important during this year as Saturn will be in the second house, and Jupiter will be aspecting the eighth house of the emotional self. You will have to focus on your diet and workout. Being Sagittarius, you will not always like a spicy diet, but it is not good to have too cold food items. Please have a balanced diet, which will help you be healthy. The facial organs and excretory area will be the highlight of this year. Those who already have issues in the facial area should take precautions. This is a very good year to correct your teeth and improve your vision. Please try to have fresh food than junk food. Those who have thyroid or alimentary canal related issues will get highlighted. The neck to shoulder area also will be susceptible, and you have to consult an ENT specialist.The yearly horoscope 2022 for Sagittarius shows the need for a better health care. That doesnt mean you will always be sickly. Things will be fine if you are already healthy, but as usual, you have to be very alert if you are going through any health issues. The mantra of fitness is knowing yourself better and dont overestimate your immunity.It will always be good to take a morning or evening walk. Sagittarius is generally a very optimistic person, and they mostly dont like physical exercises. So, you need to rethink your health in 2022, which will do well.',
  'Financial matters will be the central theme this year, which will be a problem. Saturn will be in the sign of Capricorn, and until April, it will be there itself. That will bring concerns regarding financial matters.Please try to save as much as possible as there will be unexpected expenses. You will have to make clear plans about investments; otherwise, you would not manage your money matters during the entire 2022. Your family will also need more money, and there are chances to take loans like vehicle loans, home loans, or personal loans. There will be some challenges arising from loans and partnership ventures. This is not an ideal year to have partnership projects that are too new. Please try to coordinate with your business partners too. It will not be good if you are planning everything on your own.In 2022, Sagittarius will have a lot of plans for new financial plans.You will be looking more for stability and progress, which will be possible as well. However, you should not get into any shortcuts to gain money. During the mid-portion of 2022, Rahu will come into the fifth house of speculative businesses; you will have the urge to get into some shortcuts to make money.Like every year, financial struggles will be coming in the first half of 2022. Even though you are a little frugal, during 2022, you will have to spend money for the family, as well, but there is nothing wrong with being frugal.',
  'The year 2022 will be very prominent in your life. The fourth house is activated, and the activation will be alive throughout the year. This is not bad as the fourth house is a Kendra house. However, when Saturn comes to the fourth house, you may feel burdened about your family matters. Certain real estate deals which were dragging from the last few days will be improving in the coming days. There will be progress in the real estate deals. This is a year to meet with your relatives and friends at home. Some of the relatives will move abroad, and some will come home. Specific projects were lagging at work until 2021, which will move forward from this year onwards. There will be some celebrations at home as well. You will have to take care of the elderly members of the family. Saturn means more responsibilities, and you will have to take additional responsibilities at home. The aspect of multiple planets will highlight your career-related matters. The year 2022 will be the year for multitasking, too. You will have to handle various issues at home and work. New projects from multiple domains will be coming up during this year. You will have to keep a good relationship with your managers; otherwise, there will be hurdles at work. Short projects from various communication-related domains can come up. This is a year for those who work in media and sales. Multiple planets will be impacting these matters, and you will be multitasking. You have to make some practical plans as there are chances of missing some projects. Those projects which were trailing will advance during this phase. Upskilling and short travels also can be a part of this phase. During this month, you will surely get chances to project yourself as a multitasker. This is also an excellent time to start your ventures. There will be more interaction with siblings and your other relatives. Be cautious about financial matters. You need better financial management in 2022. Please stay away from any money-making deals which are not authorized. Otherwise, there will be huge losses. Please stay away from blockchain trading as well.',
  'You will feel inactive and exhausted today. This is a total contrast to your active true self. Also youll get easily agitated today.Meditation will help you deal with the stress and tension that you suffer from. The stress would also take away your physical strength and stamina.You may now get an opportunity to hone your god-gifted talents that youve been neglecting. Your busy schedule might ease up now giving you time to pursue your interests.',
  'Your investigative and inventive mind will lead you to discover something new. Your creative discovery will also bring you lot of appreciation and recognition.You may feel drained of all your energy as you it gets wasted on an unsuccessful project youve taken up. Stop wasting your time and energy and take up something that would refresh you.Implementing any new innovation may cost you dearly. Keep aside a part of your budget to incur such costs. Avoid spending on impulse and taking any gambles.Today it would be better if you go all alone in achieving your goals. You might not find your colleagues very reliable or even co-operative.You will prefer working on your own as you detest authority. You dont like people telling you what to do and how to do it.'
  ];

  String getSagittariusInfo()=> _sagittariusInfo[0].toString();

  String getSagittariusLove()=> _sagittariusLove[0].toString();

  String getSagittariusAdvise(){
    num=Random().nextInt(6);
    return _sagittariusAdvise[num].toString();
  }
}