import 'package:flutter/material.dart';
import 'dart:math';


class TaurusInfo{

  int num=0;

  List<String> _taurusInfo=['Tauruses are hardworking, determined and loyal individuals. They value stability and security, and they are warm, gentle, sensual and highly dependable. They enjoy a full exploration of the senses and finer aspects of life. Hardworking, they take a practical approach to life and are excellent with money. They are ambitious, focused and resilient. Pleasure is what they need, and they feel most content when pampered. Taureans are stubborn and are resistant to change. They are romantics at heart who seek long-term love and happy relationships. They are perseverant whether it comes to relationships or careers. Taureans prioritise consistency and reliability in all aspects of their lives. Though occasionally obstinate, they make dependable individuals who can soothe their friends and partners with their devotion.']; 

  List<String> _taurusLove=['The planet for delays and obstacles Saturn will activate your love life and the chances for marriage during this week. This is a critical year for love and marriage. However, the main planet for love, Venus, will be in a slow down mode in January. The retrogression in transit can bring issues between you and your spouse. This is the time to meet or get some messages from the people in the past. However, this is not a great phase to restart the relationship, so you should wait for some time. There are other challenges like career and social life, and they can impact the time with your spouse. You may be working hard to bring progress, but your spouse may not understand that. In that case, you should make them understand gently.'];

  List<String> _taurusAdvise=['Career is the central theme of 2022 for Taurus as Jupiter and Saturn will be moving through Aquarius at different times. Both the planets will be igniting the career. First, you need to understand the nature of Saturn and Jupiter. Saturn is the planet for a time, and Jupiter is the one inducing the life breath to the events in your life. Please try to be flexible, and it will not do any harm to your career. You will be getting new assignments, and they will be cumbersome. This is a significant year for job seekers, and they should use this time to get new job opportunities.',
  'This is an excellent year to form long term projects for your gains. Saturn is the planet for delays, but when it starts giving results, then it will be unstoppable. For the time being, you will have to be very careful as Saturn will be impacting the ninth house of foreign collaborations and luck. So, you should not expect sudden and considerable changes in the first half of the year. Since the sixth house for debts is also active, you have to be very careful with your ongoing obligations. The universe will remind you of the need of settling some of your debts. During the first half of the year, you will think about new saving plans, but you should not hurry to take up any. In 2022, you can also expect unexpected expenses, and you have to prepare for that. The whole is showing challenges regarding money and finances.',
  'Physical and emotional health is critical in 2022. Rahu will be moving through the sign of Aries, and it will be in a very aggressive mode. So, you will have to take care of your emotional health than physical health. Rahu doesnt like to be in the twelfth house of emotional nature, as it is the planet for conquering everything. In the twelfth house, it is shut down from the material pleasures and forced to be in the sector for spirituality. Usually, you are a calm person, but you will have concerns regarding your health and emotional needs during this Rahu transit. Ketu will be impacting the sixth house of health as well. You will have to take care of your diet. The sixth house Ketu is transiting indicates your lower abdomen area, and that will be a concern. Those suffering from lifestyle diseases like diabetes, cholesterol or hypertension should see this as a complex time. They should take the proper medication and should have regular checks up as well. The importance of diet is very high during this time. If you like to go for prayer and meditation, this is the best time for it.',
  'You have the ability to understand others feelings and emotions. It makes you empathize with them and their situations. But today, its best that you explain your views and opinions clearly so that you are not misunderstood.You have been suffering from hallucinations and nightmares. Today you might receive proper guidance from a qualified person who will help you rid of these.Today it would be better if you go all alone in achieving your goals. You might not find your colleagues very reliable or even co-operative.Although you might be caught up with work, today you should steal some moments to share with your beloved. This time together will help strengthen your bond. And because you are very much in love, you will find the means to do this.You will soon find yourself in a new surrounding. It might be a transfer or a shift to a new place. But this move will definitely bring about a positive change in your nature.',
  'Start referring to books related to what you intend to do. Such books will guide you in making successful plans.Today you may feel exhausted of the demands made on you at home as well as at work. You need to take some time out and think and plan your work. For all you know, you might be doing something the hard way.It would be good if you do not take any risks in business or industrial matters. Such a risk might jeopardize you and your position.Try and analyze the reasons or basis for the interest you have developed in a new acquaintance. Do not place your trust on anyone before you know them well.Your habit of thinking beyond the good and the bad and of finding something wonderful about others will gain you loyalties of those around you. They will be loving and true to you.',
  'A balancing act between developing yourself and your romantic relationship, versus your obligations to your group associates or projects is likely to stretch your limits. So, your energy has to be well spent.Approval of a new project by the authority will give you the opportunity of expanding and implementing new ideas which were only in your mind till now.Your talents will get a proper guidance and you will also get rid of the fallacies that were in your mind since your childhood.Although you are restless, impulsive and looking for the wildest kind of excitement, your easy going and loving nature will help you to get pardoned for your follies.You may feel down and depressed as things may not be going according to your expectations. Let this not make you lethargic and demotivate you. This may only be a small hurdle in one of the lifes journeys. Remember you have a goal to fulfil.Think more about the prospects for your personal growth, as it is time for you to live for you and your family.You need plenty of changes and challenges these days to boost up your physical stamina. Monotony and persistent lack of stimulation need to be guarded against.Work is your source of excitement and youll not give your body a rest even when you feel exhausted. But, this week will bring an absolute change in you, making you wish for a refreshing mood, to rejuvenate your mind and body.Just go around socialising and throw lavish parties which will bring you attached to some beautiful and romantic people, who can bring a change to the lifestyle as well as the dullness of your life.New atmosphere and new friends will be a real experience for you. Your active presence will reform your friends also.'
  ];

  String getTaurusInfo()=> _taurusInfo[0].toString();
     
  
  String getTaurusLove()=> _taurusLove[0].toString();

  String getTaurusAdvise(){
    num=Random().nextInt(6);
    return _taurusAdvise[num].toString();
  }

}