import 'dart:math';
import 'package:flutter/material.dart';


class VirgoInfo{

  int num=0;

  List<String> _virgoInfo=['Virgos are kind, grounded and trustworthy. They are practical, hardworking and analytical. They can assess the details and find solutions to problems. They are natural-born organisers. Virgos values loyalty, productivity and consistency. They invest too much of themselves into achieving their goals and plans; however, they can be critical if things do not progress as initially expected. They are perfectionists, which can grow into an obsession. They are happy to help anyone they love who needs their help. Their tenacity and intellectualism help them to create order out of chaos. They are even-tempered and love absorbing information. Virgos are known for their quick wit and dry sense of humour.'];

  List<String> _virgoLove=['This is a very important year for Virgo natives. They will get many opportunities to find like-minded people and start a new relationship. Jupiter will be moving into the sign of Pisces after mid-April. This will bring chances to meet new people. During the early part of the year, Venus will be moving slowly. So it is best not to take any risk with new relationships in that period. But during the first four months, Saturn will influence love and marriage. Which means you can work on improving an existing relationship. 2022 brings singles plenty of opportunities to meet and get to know new people. This is also an excellent year to get married. There are chances for long trips, and you may meet people during these journeys. Mercury will be in retrogression every three months, so please dont hurry to make any commitments during that time.'];

  List<String> _virgoAdvise=['This is a crucial year for careerists as well as business people. The importance of both matters will be predominant during this year. Both the planets, Saturn and Jupiter, will impact your job, and you will feel the need to improve your career. There are chances of disagreements with colleagues. It would be best to avoid unnecessary interaction with them. Maintain a professional relationship with them. It is not wise to make them a part of your life as they may misuse your trust. Those trying to find a new job will have a critical but fruitful time this year. Business people should be cautious as there will be blockages in the deals. Please dont take any considerable risk in the business. This is not a year to make any significant investment plans; if you take such risks, you should think twice. This will be a slightly slow year for those who work in the creative domain.',
  'This is a crucial year for health as Jupiter and Saturn will be moving through the sixth physical health house. These planets will impact the lower abdomen area, so you will have to take care. This is a sensitive transit and your diet and nutrition. You will have to be very careful if you already have lifestyle diseases as Jupiter and Saturn will highlight these issues. This is an excellent year to focus on improving your mental health too. You will be interested in various ways of healing too. This is also a crucial phase for those planning to have children. The pregnant woman also should take enough precautions. Those facing some difficulty in childbirth will find good opportunities to take remedies. You will have to take care of the children around you also. The older people in the family also will need more care.',
  'Your financial progress will not be delayed or stuck for a long time, but some financial concerns will be. During 2022 both the planets Saturn and Jupiter will be moving through the sixth house of debts, so there will be concerns regarding wealth. You will have to take care of your existing debts. From April onwards, Saturn will discuss loans and other kinds of investments. Please dont be so confident about the repayment. There will be some plans for settling the existing loans as well. You will have to resolve some issues in tax and investments as well. Try to refrain from too many expenses as the second house of money also will be activated. This will surely bring more money, but that will also force you to spend it. Your focus should be on making more money and saving it. Unexpected expenses also will be coming up during 2022.',
  'You will find it very difficult today to be kind to or forgive someone who has done you any harm. It requires a higher consciousness to be able to do so. But your ability to be empathetic towards everyone helps you forgive such a person.You will meet a qualified doctor or someone equally knowledgeable who will help you out of your illusory world. It has been taking you away from the real world.Today you will need all the encouragement and motivation you can get. But unfortunately your stars are not favorable and you might not receive the assistance you require today.Today an important issue might be brought up by your beloved. Give all your attention and priority to what seems to be the concern.Today you can expect something that refreshed and rejuvenates you. It might be a good news, or someone who makes you happy. Keep up the high spirits.',
  'Your ability to experiment will prove to be a boon for you and you will be using this resource of yours to make everyone stand up and take notice of you.You are pressed to retrace back in the workplace or with your partner. A critical situation is developing around you and though it gets on your nerves, you may be the only one who can appear to remain calm and unbiased.Your peculiarities, which were a source for others to make fun of you, will bring some advantages for you this week. You will find yourself a central figure in some parties or public gatherings.A balancing act between developing yourself and your romantic relationship, versus your obligations to your group associates or projects is likely to stretch your limits. So, your energy has to be well spent.Both at workplace and home, your innovative nature will help you keep up the tempo and bring more enjoyment to your life. Keep it up and monotony in life will be a thing of the past, forgotten and buried!You may feel down and depressed as things may not be going according to your expectations. Let this not make you lethargic and demotivate you. This may only be a small hurdle in one of the lifes journeys. Remember you have a goal to fulfil.As a born leader, you are a pioneer with a purpose. You tend to reach your goals in straightforward ways and without hurting anyone.Your ability to remain silent, humble and flexible when it is not necessary to air your views will bring more recognition for you among others. You can very well present your philosophical insights when it is in need.The main menace to your physical situation will be your emotions, which in the form of repressed anger and grudges can even lead to a mental syndrome.An unexpected approach from an unexpected person will make your days harmonious. Utilise this opportunity without wasting it.',
  'Today you may feel exhausted of the demands made on you at home as well as at work. You need to take some time out and think and plan your work. For all you know, you might be doing something the hard way.Lack of physical stamina will lead you to procrastinate. You wont be up to implementing your ideas instead you would spend your time thinking and analyzing.You will find time today to pursue your favorite hobbies and interests. This will refresh and invigorate you. And also create a mental balance as all work and no play makes you a dull person.'
  ];

  String getVirgoInfo()=> _virgoInfo[0].toString();

  String getVirgoLove()=> _virgoLove[0].toString();

  String getVirgoAdvise(){
    num=Random().nextInt(6);
    return _virgoAdvise[num].toString();
  }
}